### ISSUE TITLE
Prepare slides for presentation at the Kickoff

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#15]
@caathytraan and @linamoon will create content - designers @dalalpreet and @asparks will create template (ty!)

**Comment by dalalpreet** [comment]
The template's up here! 
https://drive.google.com/open?id=0B6XuQtWg2aKqQ3NYaE13LWhJR00

So create content whenever you need to!

**Comment by linamoon** [comment]
Done by @linamoon in Illustrator, presented at the kickoff.
