### ISSUE TITLE
Design flyers and social media posts

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#2]
- Print flyers
- Covers on the website
- Facebook
- Twitter
- Banner (for photobooth)

Coordinate with @asparks and @piengel

**Comment by dalalpreet** [comment]
Finished creating the flyers. Posted here:
https://drive.google.com/drive/folders/0B6XuQtWg2aKqUkVOaDVld3V6bTQ

I'm really sick with wisdom tooth infection, so as mentioned on slack, if people can print these themselves, that would be cool.
