### ISSUE TITLE
Buy props for Kickoff event and bring to next officer meeting

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#21]
- little UX signs on wooden sticks
- wireframes
- UX glasses
- mustaches
- emojis

---------------------
- wooden sticks
- glitter
- hot glue gun 
- colored paper - 50 shades of blue and others
- feathers
- puff paint

Angela meets up with Ola and Chisom to coordinate a time to get Chisom on the card - Chisom coordinates with Angela for time to shop

**Comment by angelakou** [comment]
• Construction paper (Lots)
• Glitter
• Paint Pens
• Wooden Sticks
• Poster boards 
• Paint and brushes (?)
• Cardboard

**Comment by linamoon** [comment]
Officers will work on props during meeting - use above as reference for budgeting with @chisomekweani
