### ISSUE TITLE
Poll members on event to pass out at Kickoff

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#22]
- Give out people flyers at beginning of event - what events they would like, etc.
- Flyer will go into a raffle box for prize draw (prizes are books, maybe something from Capital One)

**Comment by 01parkelly** [comment]
I would love other people's input on what questions to ask. For rating the event part, I don't know if 1 to 5 scale work better or just simply asking them things we can improve? Please feel free to edit or add to this. Thanks! 

https://docs.google.com/document/d/1PSujVf_vGjI-TLNawklh2aABIPmOfFDpCiCALwZFnU8/edit?usp=sharing

**Comment by linamoon** [comment]
@a-sparks and @dalalpreet priority before the kickoff to design flyers survey/raffle ticket - can print at the SOC office
