### ISSUE TITLE
Props/biz cards in budget 

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#25]

**Comment by chisomekweani** [comment]
Business cards from staples would cost us $9.99 for 500 cards for each person. Each card would be one-sided color and could be done same day.
Vista Print would cost us $7.99 for a quantity of 100 each for the same standard.

**Comment by linamoon** [comment]
Muchos gracias @chisomekweani! Please contact @01parkelly about implementation and design (it's very convenient that it can be done same day)

**Comment by chisomekweani** [comment]
Okay perfect I will, I'm going to contact parkelly

**Comment by 01parkelly** [comment]
Here is the details for business cards. I think they need to be 2-sided printing. 
Plus, I think full color and one-color have different prices as well? We need to decide this before designers @a-sparks @dalalpreet  start designing.

https://docs.google.com/document/d/1bEhP8e71Vu8XvnupyzqE93XbasBj6MQYz2pt8PTSzDk/edit?usp=sharing

**Comment by linamoon** [comment]
@chisomekweani I think 2-sided printing would be ideal as well - would want to look into this. Might also want to look into https://www.moo.com/us/ for their prices, since I think people use them a lot for cards.

**Comment by chisomekweani** [comment]
http://www.staples.com/sbd/content/copyandprint/businesscards.html

**Comment by linamoon** [comment]
@a-sparks and @dalalpreet work on potential designs for business card

**Comment by linamoon** [comment]
Moved to issue https://github.com/uxutdallas/uxutdallas/issues/4
