### ISSUE TITLE
Create poll for deciding community dinner at the kickoff

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#38]
Put account information in this document here: https://docs.google.com/document/d/10DO_0KPPuunT17yemLGrTGTzlm-6jH8RSSCB37h-l_4/edit

**Comment by linamoon** [comment]
@01parkelly Would like to make final list of places (4 options) to present at Kickoff.

**Comment by caathytraan** [comment]
https://getkahoot.com/ 
username: uxutdallas@gmail.com
password: thinkUX#1

**Comment by linamoon** [comment]
Not implemented due to the fact that we would like to reserve a restaurant first - will take note of this
