### ISSUE TITLE
Student engagement - Create sign-in sheet for Kickoff

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/kickoffparty#7]
To add to mailing list
- Name
- Major
- Email

**Comment by angelakou** [comment]
@dalalpreet @01parkelly @asparks

**Comment by dalalpreet** [comment]
Finished the graphic! Uploaded on
 https://drive.google.com/open?id=0B6XuQtWg2aKqYVBXbnRNVFNrRWc
